#!/bin/sh
#github -> https://github.com/liupold/pidswallow
swallowable=" $TERMINAL urxvt kitty "
blacklist=" $swallowable octave-gui python " # you don't want to swallow a swalloer right?
verbose=0

swallow() {
        cwid="$1"; pwid="$2"; cname="$3"; pname="$4";
        [ "${blacklist#* $cname }" != "$blacklist" ] && return
        bspc node "$pwid" --flag hidden=on                      #*
        [ "$verbose" -eq 1 ] && echo "$cname($cwid) swallowed $pname($pwid)"
        echo "$pwid" > "/tmp/swallowed-by-$cwid"
}
vomit() {
        cwid="$1"
        [ -f "/tmp/swallowed-by-$cwid" ] || exit 2
        pwid=$(cat "/tmp/swallowed-by-$cwid")
        bspc node "$pwid" --flag hidden=off  -f                  #*
        [ "$verbose" -eq 1 ] && echo "$cwid vomited $pwid"
        rm "/tmp/swallowed-by-$cwid"; exit
}

cwid="$1"
cpid=$(xprop _NET_WM_PID -id "$cwid" 2>/dev/null); xprop_ret="$?"
[ -f "/tmp/swallowed-by-$cwid" ] && vomit "$cwid"
[ "$xprop_ret" -ne 0 ] && vomit "$cwid"

cpid="${cpid##* }"
cname="$(cat /proc/"$cpid"/comm)"

for parrent in $(pstree -ATsp "$cpid" | sed -e 's|(|:|g' -e 's|)||g' -e 's|---|\n|g' | tac)
do
        aname="$(echo "$parrent" | cut -d':' -f1)" # ancestor name
        [ "${swallowable#* $aname}" != "$swallowable" ] \
                && ppid="$(echo "$parrent" | cut -d':' -f2)" && pname="$aname" && break
done

[ -z "$pname" ] && exit 1 # nothing swallow able.
pwid="$(xdotool search --pid "$ppid" 2>/dev/null)"
swallow "$cwid" "$pwid" "$cname" "$pname"
