#!/bin/sh

terminal_pid="$1"
terminal_class="$2"

if [ -n "$DISPLAY" ] && which xdo >/dev/null 2>&1; then
        attempt=0
        while [ "$attempt" -lt 5 ]; do
                terminal_wid="$(xdo id -m)"
                if [ ! -f "/tmp/term-pid-$terminal_wid" ] && [ "$(xdo id -N "$terminal_class" "$terminal_wid")" ]; then
                        echo "$terminal_pid" > /tmp/term-pid-"$terminal_wid"
                        echo "$terminal_wid" > /tmp/term-wid-"$terminal_pid"
                        echo "$terminal_wid" # output for trap
                        break
                else
                        attempt=$(( attempt + 1 ))
                        sleep 0.1
                        false # to exit with error code if loop wasn't broken above
                fi
        done
fi

