#!/bin/sh
useage="pidswallow (pid swallow for bspwm)
Hides terminal window automatically, so that you don't have to

pidswallow [OPTION ...]

OPTIONS:
        -h  --help              Show this message
        -l  --loop              listen and hide / unhide window on launch / remove.
        -s  --swallow <CWID>    Hides parent window of the given child window id.
        -v  --vomit <CWID>      Unhides parent window of the given child window id.
        -t  --toggle <CWID>     toggle between swallow and vomit. (default)
        -V  --verbose           Shows usefull information.

bugs/issues: https://github.com/liupold/pidswallow.
"
swallowable=" $TERMINAL urxvt kitty "
blacklist=" $swallowable octave-gui python "
verbose=0

vomit() {
        [ -f "/tmp/swallowed-by-$cwid" ] || return 1
        cwid="$1"
        pwid=$(cat "/tmp/swallowed-by-$cwid")
        bspc node "$pwid" --flag hidden=off  -f                  #*
        [ "$verbose" -eq 1 ] && echo "$cwid vomited $pwid"
        rm "/tmp/swallowed-by-$cwid"; return 0
}

swallow() {
        cwid="$1"
        cpid="$(xprop _NET_WM_PID -id "$cwid" 2>/dev/null)"
        [ "$?" -ne 0 ] && return 1
        [ "${cpid#*not found*}" != "$cpid" ] && return 1 # window didn't have _NET_WM_PID
        cpid="${cpid##* }"
        cname="$(ps -p "$cpid" -o comm=)"
        [ "${blacklist#* $cname }" != "$blacklist" ] && return 0
        for parrent in $(pstree -ATsp "$cpid" \
                | sed -e 's|(|:|g' -e 's|)||g' -e 's|---|\n|g' | tac); do

                pname="${parrent%%:*}" # ancestor name
                [ "${swallowable#* $pname}" != "$swallowable" ] \
                        && ppid="${parrent##*:}" && break
        done
        [ -z "$ppid" ] && return 1 # nothing swallow able.
        pwid="$(xdotool search --pid "$ppid" 2>/dev/null)"
        bspc node "$pwid" --flag hidden=on                      #*
        [ "$verbose" -eq 1 ] && echo "$cname($cwid) swallowed $pname($pwid)"
        echo "$pwid" > "/tmp/swallowed-by-$cwid"
}

toggle() {
        cwid="$1"
        if [ -f "/tmp/swallowed-by-$cwid" ]; then
                vomit "$cwid"
                exit "$?"
        else
                swallow "$cwid"
                exit "$?"
        fi
}

loop() { #*
        while true; do
                event="$(bspc subscribe -c 1 node_add node_remove)"
                [ "${event#node_add}" != "$event" ] && swallow "${event##* }"
                [ "${event#node_remove}" != "$event" ] && vomit "${event##* }"
        done
}

[ "$#" -eq 0 ] && echo "$useage" && exit 1

TEMP=$(getopt -o 'Vhlt:s:v:' --long 'verbose,help,loop,toggle:,swallow:,vomit:' \
        -n 'pidswallow' -- "$@")
eval set -- "${TEMP}"; unset TEMP

while true; do
        case "$1" in
                '-h' | '--help' )
                        echo "$useage" && exit 0;;
                '-V'|'--verbose')
                        verbose=1
                        shift; continue;;
                '-t'|'--toggle')
                        toggle "$2"
                        shift 2; continue;;
                '-s'|'--swallow')
                        swallow "$2"
                        shift 2; continue;;
                '-v'|'--vomit')
                        swallow "$2"
                        shift 2; continue;;
                '-l'|'--loop')
                        loop
                        shift; continue;;
                '--')
                        shift; break;;
                *)
                        echo "Internal error!" >&2
                        echo "$useage" && exit 1;;
        esac
done
[ -n "$*" ] && toggle "$1"; shift
[ -n "$*" ] && echo "Unrecognized trailing option '$*'" >&2 && exit 1
