on:
  push:
    branch:
      - master
      - dev
      - aur

name: 'Trigger: Push action'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
  make-pkgbuild:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: make pkgbuild from template
      run: .github/update-pkgbuild.sh
  build-dev:
    needs: make-pkgbuild
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v2
      - name: Build Arch Linux package
        uses: FFY00/build-arch-package@master
        with:
          PKGBUILD: $GITHUB_WORKSPACE/.github/aur/git/PKGBUILD
